### ISSUE TITLE
Adjust the property list items labels in the GUI

### ISSUE THREAD

**Issue by diegoesteves** [SmartDataAnalytics/DeFacto#10]
wrong -> correct
http://dbpedia.org/ontology/publicationDate -> http://dbpedia.org/ontology/author
http://dbpedia.org/ontology/playedTeam -> http://dbpedia.org/ontology/nflTeam
http://dbpedia.org/ontology/inOffice -> http://dbpedia.org/ontology/leaderName

**Comment by renespeck** [comment]
I just copied the file
https://github.com/AKSW/DeFacto/blob/fusion/defacto-gui/src/main/resources/supported_relations.txt 
to 
https://github.com/AKSW/DeFacto/blob/fusion/defacto-restful/src/main/resources
and used it like it is since 2013. :smile: :
