### ISSUE TITLE
Missing Files?

### ISSUE THREAD

**Issue by KevinBassaDevelopment** [SmartDataAnalytics/DeFacto#21]
Hi, I'm not familiar with DeFacto and want to get it running.

> If you want to try Defacto all you need to do is:
> 1. Check out DeFacto in Eclipse (via check out maven repo from SCM)
> 2. copy defacto.ini.default to defacto.ini
> 3. get your own bing search api key
> 4. write this key to the defacto.ini (adjust your settings)
> 5. run DefactoDemo.java

When running DefactoDemo.java, I get the error message: 

> Install the surface form file to resources/cache/labels/en_uri_surface_form.tsv!

Where do I get this data from? 

I appreciate any hint.

**Comment by dnes85** [comment]
Hi Kevin,

this file is no longer necessary. Could you please try the branch prod_JWS_2015 and update me here?

Cheers,
D.Esteves.

**Comment by KevinBassaDevelopment** [comment]
Ok, I branched prod_JWS_2015 and it compiles just fine, but I'm also not able to get it running.
Is there anything else that needs to be done except the 5 steps mentioned on the readme?

In the Demo, and RDF tripple with http://dbpedia.org/resource/Manchester_United_F.C and http://dbpedia.org/resource/Cristiano_Ronaldo is created - but it doesn't properly initialize this model. 
After initialization, DefactoResource subject & DefactoResource object are still null, which leads to an error at the first time logging where it tries to get log the name of these two - so it doesnt even start running. 
How can I get the initialization right?
Thanks in advance for any help - I do appreciate this very much.

**Comment by dnes85** [comment]
Hi Kevin,
sorry for the late reply.
could you send me the log file (esteves at informatik dot uni dash leipzig dot de)? Did you setup the solr instance locally? Did you get our BING api ? Have you changed the .ini file with your parameters?

Kind Regards,
D.Esteves

**Comment by dnes85** [comment]
Hi @KevinBassaDevelopment, have you check my remarks? All clear?
